### ISSUE TITLE
Cannot read property 'addLayer'

### ISSUE THREAD

**Issue by Xeanor-V** [TA-Geoforce/react-leaflet-bing-v2#1]
Hello,

I have just switched from using the old react-leaflet-bing to this new version and I'm
receiving the following error:

![image](https://user-images.githubusercontent.com/10505010/69293948-42775f80-0bbf-11ea-8d22-d00e83bc7b98.png)

On my side the code has not changed at all compared to the old version, could this be a dependecy issue of some sort?

**Comment by barbalex** [comment]
There is also a `removeLayer` variation of this error:

```
MapLayer.js:38 Uncaught TypeError: Cannot read property 'addLayer' of undefined
    at BingLayer.componentDidMount (MapLayer.js:38)
    at BingLayer.componentDidMount (react-hot-loader.development.js:707)
    at commitLifeCycles (react-dom.development.js:20663)
    at commitLayoutEffects (react-dom.development.js:23426)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at commitRootImpl (react-dom.development.js:23151)
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
    at commitRoot (react-dom.development.js:22990)
    at performSyncWorkOnRoot (react-dom.development.js:22329)
    at react-dom.development.js:11327
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322)
    at flushSyncCallbackQueue (react-dom.development.js:11309)
    at flushPendingDiscreteUpdates (react-dom.development.js:22372)
    at flushDiscreteUpdates (react-dom.development.js:22353)
    at finishEventHandler (react-dom.development.js:3714)
    at batchedEventUpdates (react-dom.development.js:3748)
    at dispatchEventForPluginEventSystem (react-dom.development.js:8507)
    at attemptToDispatchEvent (react-dom.development.js:6005)
    at dispatchEvent (react-dom.development.js:5924)
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
    at discreteUpdates$1 (react-dom.development.js:22413)
    at discreteUpdates (react-dom.development.js:3756)
    at dispatchDiscreteEvent (react-dom.development.js:5889)
componentDidMount @ MapLayer.js:38
componentDidMount @ react-hot-loader.development.js:707
commitLifeCycles @ react-dom.development.js:20663
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
flushPendingDiscreteUpdates @ react-dom.development.js:22372
flushDiscreteUpdates @ react-dom.development.js:22353
finishEventHandler @ react-dom.development.js:3714
batchedEventUpdates @ react-dom.development.js:3748
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889



index.js:2177 The above error occurred in the <BingLayer> component:

    at BingLayer (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at Leaflet(BingLayer)
    at BingAerialLayer
    at BingAerial
    at div
    at MapContainer (http://localhost:8000/commons.js:235084:20)
    at Karte__StyledMapContainer (http://localhost:8000/commons.js:305889:19472)
    at ErrorBoundary (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at MyErrorBoundary (http://localhost:8000/commons.js:235084:20)
    at div
    at Karte__Container (http://localhost:8000/commons.js:305889:19472)
    at Karte (http://localhost:8000/commons.js:235084:20)
    at _default (http://localhost:8000/commons.js:235084:20)
    at div
    at ProjektContainer__InnerContainer (http://localhost:8000/commons.js:305889:19472)
    at div
    at Pane (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at div
    at SplitPane (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at ProjektContainer__StyledSplitPane (http://localhost:8000/commons.js:305889:19472)
    at div
    at ProjektContainer__Container (http://localhost:8000/commons.js:305889:19472)
    at ProjektContainer (http://localhost:8000/commons.js:169383:80)
    at ResizeDetector (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at ResizeDetectorHOC (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at withResizeDetector(ProjektContainer)
    at div
    at Projekte__Container (http://localhost:8000/commons.js:305889:19472)
    at Projekte (http://localhost:8000/commons.js:235084:20)
    at div
    at Daten__Container (http://localhost:8000/commons.js:305889:19472)
    at div
    at Layout__ContentContainer (http://localhost:8000/commons.js:305889:19472)
    at div
    at Layout__Container (http://localhost:8000/commons.js:305889:19472)
    at Layout (http://localhost:8000/commons.js:235084:20)
    at ErrorBoundary (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at MyErrorBoundary (http://localhost:8000/commons.js:235084:20)
    at DatenPage (http://localhost:8000/commons.js:235084:20)
    at AppContainer (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at HotExportedDatenPage (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at PageRenderer (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at PageQueryStore (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at RouteHandler
    at div
    at FocusHandlerImpl (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at FocusHandler (http://localhost:8000/commons.js:235084:20)
    at RouterImpl (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at Location (http://localhost:8000/commons.js:235084:20)
    at Router
    at ScrollHandler (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at RouteUpdates (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at EnsureResources (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at LocationHandler (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at LocationProvider (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at Location (http://localhost:8000/commons.js:235084:20)
    at Root
    at SnackbarProvider (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at ThemeProvider (http://localhost:8000/commons.js:235084:20)
    at ApolloProvider (http://localhost:8000/commons.js:235084:20)
    at App (http://localhost:8000/commons.js:235084:20)
    at StaticQueryStore (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at ConditionalFastRefreshOverlay (http://localhost:8000/commons.js:235084:20)
    at _default

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
__stack_frame_overlay_proxy_console__ @ index.js:2177
overrideMethod @ react_devtools_backend.js:2430
logCapturedError @ react-dom.development.js:20085
update.payload @ react-dom.development.js:20133
getStateFromUpdate @ react-dom.development.js:12102
processUpdateQueue @ react-dom.development.js:12250
updateClassInstance @ react-dom.development.js:13013
updateClassComponent @ react-dom.development.js:17432
beginWork @ react-dom.development.js:19073
beginWork$1 @ react-dom.development.js:23940
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
flushPendingDiscreteUpdates @ react-dom.development.js:22372
flushDiscreteUpdates @ react-dom.development.js:22353
finishEventHandler @ react-dom.development.js:3714
batchedEventUpdates @ react-dom.development.js:3748
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
MapLayer.js:59 Uncaught TypeError: Cannot read property 'removeLayer' of undefined
    at BingLayer.componentWillUnmount (MapLayer.js:59)
    at BingLayer.componentWillUnmount (react-hot-loader.development.js:707)
    at callComponentWillUnmountWithTimer (react-dom.development.js:20413)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at safelyCallComponentWillUnmount (react-dom.development.js:20420)
    at commitUnmount (react-dom.development.js:20951)
    at commitNestedUnmounts (react-dom.development.js:21004)
    at unmountHostComponents (react-dom.development.js:21290)
    at commitDeletion (react-dom.development.js:21347)
    at commitMutationEffects (react-dom.development.js:23407)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at commitRootImpl (react-dom.development.js:23121)
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
    at commitRoot (react-dom.development.js:22990)
    at performSyncWorkOnRoot (react-dom.development.js:22329)
    at react-dom.development.js:11327
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322)
    at flushSyncCallbackQueue (react-dom.development.js:11309)
    at flushPendingDiscreteUpdates (react-dom.development.js:22372)
    at flushDiscreteUpdates (react-dom.development.js:22353)
    at finishEventHandler (react-dom.development.js:3714)
    at batchedEventUpdates (react-dom.development.js:3748)
    at dispatchEventForPluginEventSystem (react-dom.development.js:8507)
    at attemptToDispatchEvent (react-dom.development.js:6005)
    at dispatchEvent (react-dom.development.js:5924)
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
    at discreteUpdates$1 (react-dom.development.js:22413)
    at discreteUpdates (react-dom.development.js:3756)
    at dispatchDiscreteEvent (react-dom.development.js:5889)
componentWillUnmount @ MapLayer.js:59
componentWillUnmount @ react-hot-loader.development.js:707
callComponentWillUnmountWithTimer @ react-dom.development.js:20413
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
safelyCallComponentWillUnmount @ react-dom.development.js:20420
commitUnmount @ react-dom.development.js:20951
commitNestedUnmounts @ react-dom.development.js:21004
unmountHostComponents @ react-dom.development.js:21290
commitDeletion @ react-dom.development.js:21347
commitMutationEffects @ react-dom.development.js:23407
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23121
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
flushPendingDiscreteUpdates @ react-dom.development.js:22372
flushDiscreteUpdates @ react-dom.development.js:22353
finishEventHandler @ react-dom.development.js:3714
batchedEventUpdates @ react-dom.development.js:3748
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
Show 7 more frames from Library code



index.js:2177 The above error occurred in the <BingLayer> component:

    at BingLayer (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at Leaflet(BingLayer)
    at BingAerialLayer
    at BingAerial
    at div
    at MapContainer (http://localhost:8000/commons.js:235084:20)
    at Karte__StyledMapContainer (http://localhost:8000/commons.js:305889:19472)
    at ErrorBoundary (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at MyErrorBoundary (http://localhost:8000/commons.js:235084:20)
    at div
    at Karte__Container (http://localhost:8000/commons.js:305889:19472)
    at Karte (http://localhost:8000/commons.js:235084:20)
    at _default (http://localhost:8000/commons.js:235084:20)
    at div
    at ProjektContainer__InnerContainer (http://localhost:8000/commons.js:305889:19472)
    at div
    at Pane (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at div
    at SplitPane (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at ProjektContainer__StyledSplitPane (http://localhost:8000/commons.js:305889:19472)
    at div
    at ProjektContainer__Container (http://localhost:8000/commons.js:305889:19472)
    at ProjektContainer (http://localhost:8000/commons.js:169383:80)
    at ResizeDetector (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at ResizeDetectorHOC (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at withResizeDetector(ProjektContainer)
    at div
    at Projekte__Container (http://localhost:8000/commons.js:305889:19472)
    at Projekte (http://localhost:8000/commons.js:235084:20)
    at div
    at Daten__Container (http://localhost:8000/commons.js:305889:19472)
    at div
    at Layout__ContentContainer (http://localhost:8000/commons.js:305889:19472)
    at div
    at Layout__Container (http://localhost:8000/commons.js:305889:19472)
    at Layout (http://localhost:8000/commons.js:235084:20)
    at ErrorBoundary (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at MyErrorBoundary (http://localhost:8000/commons.js:235084:20)
    at DatenPage (http://localhost:8000/commons.js:235084:20)
    at AppContainer (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at HotExportedDatenPage (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at PageRenderer (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at PageQueryStore (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at RouteHandler
    at div
    at FocusHandlerImpl (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at FocusHandler (http://localhost:8000/commons.js:235084:20)
    at RouterImpl (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at Location (http://localhost:8000/commons.js:235084:20)
    at Router
    at ScrollHandler (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at RouteUpdates (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at EnsureResources (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at LocationHandler (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at LocationProvider (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at Location (http://localhost:8000/commons.js:235084:20)
    at Root
    at SnackbarProvider (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at ThemeProvider (http://localhost:8000/commons.js:235084:20)
    at ApolloProvider (http://localhost:8000/commons.js:235084:20)
    at App (http://localhost:8000/commons.js:235084:20)
    at StaticQueryStore (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:234589:10), <anonymous>:14:7)
    at ConditionalFastRefreshOverlay (http://localhost:8000/commons.js:235084:20)
    at _default

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
__stack_frame_overlay_proxy_console__ @ index.js:2177
overrideMethod @ react_devtools_backend.js:2430
logCapturedError @ react-dom.development.js:20085
update.payload @ react-dom.development.js:20133
getStateFromUpdate @ react-dom.development.js:12102
processUpdateQueue @ react-dom.development.js:12250
updateClassInstance @ react-dom.development.js:13013
updateClassComponent @ react-dom.development.js:17432
beginWork @ react-dom.development.js:19073
beginWork$1 @ react-dom.development.js:23940
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
flushPendingDiscreteUpdates @ react-dom.development.js:22372
flushDiscreteUpdates @ react-dom.development.js:22353
finishEventHandler @ react-dom.development.js:3714
batchedEventUpdates @ react-dom.development.js:3748
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
```

**Comment by Mylothros-Charalampos** [comment]
the repo is updated please try to update it and if the error still persist open a new issue :)

**Comment by barbalex** [comment]
Works for me. Thanks!
